import { NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email';
import { ADMIN_ALERT_EMAIL } from '@/lib/role-config';

export async function POST(request: Request) {
  try {
    const { error, digest, path, userAgent } = await request.json();

    const emailHtml = `
      <div style="font-family: sans-serif; padding: 20px; color: #111;">
        <h2 style="color: #e11d48; margin-top: 0;">🚨 7th Heaven Application Error Alert</h2>
        <p>A runtime error was caught by the Next.js Error Boundary.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; width: 120px;">Path</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-family: monospace;">${path || 'Unknown'}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Digest</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-family: monospace;">${digest || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">User Agent</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-family: monospace; font-size: 12px;">${userAgent || 'Unknown'}</td>
          </tr>
        </table>

        <h3 style="margin-top: 30px; border-bottom: 2px solid #eee; padding-bottom: 5px;">Error Details</h3>
        <pre style="background: #f1f5f9; padding: 15px; border-radius: 6px; overflow-x: auto; font-size: 13px; line-height: 1.5; color: #334155; border: 1px solid #e2e8f0;">${error || 'No error details provided'}</pre>
        
        <p style="margin-top: 30px; font-size: 12px; color: #64748b;">
          This is an automated alert generated by the 7th Heaven Error Boundary.
        </p>
      </div>
    `;

    const result = await sendEmail({
      to: ADMIN_ALERT_EMAIL || 'admin@7thheavenband.com',
      subject: '🚨 [7th Heaven] Application Error Detected',
      html: emailHtml,
    });

    return NextResponse.json({ success: true, result });
  } catch (error: any) {
    console.error('Error in /api/report-error:', error);
    return NextResponse.json({ error: error.message }, { status: 200 });
  }
}
