import { createClient } from "@sanity/client";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "1dg5ciuj";
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const token = process.env.SANITY_API_TOKEN;

if (!token) {
  console.error("Missing SANITY_API_TOKEN in .env.local");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  useCdn: false,
  token,
});

const MEMBERS = [
  {
    _id: "bandMember-frankie-harchut",
    _type: "bandMember",
    name: "Frankie Harchut",
    slug: { _type: "slug", current: "frankie-harchut" },
    fullName: "FRANKIE HARCHUT",
    memberNo: "NO. 005",
    role: "Drums • Percussion",
    birthday: "May 31",
    zodiac: "Gemini",
    luckyNo: "5",
    color: "Crimson Red",
    bestTrait: "Care For Others",
    worstTrait: "Care For Others",
    favQuote: "Success is where preparation and opportunity meet.",
    favLoveSong: '"Everlong" — Foo Fighters',
    favRockSong: '"Denial" — Sevendust',
    favAlbum: "Throwing Copper — Live",
    favBands: "Sevendust, Korn, A Day To Remember",
    favSoundtrack: "My Cousin Vinny, Casino",
    favMovie: "My Cousin Vinny, Casino",
    fav7hSong: '"Midwest Girls In The Summertime"',
    firstSong: "Wipe Out",
    firstSongLearned: "Wipe Out",
    favPlaceToPlay: "High-energy festival main stages",
    bestConcertSeen: "Korn & Sevendust live",
    favTvShow: "The Sopranos, Peaky Blinders",
    favCartoon: "The Simpsons",
    favMagazine: "Modern Drummer",
    hobbies: "Cooking Polish feast recipes",
    hobbyAwayFromBand: "Cooking Polish feast recipes",
    bestFeeling: "Locking in a powerful drum beat with the crowd jumping",
    bestFeelingInWorld: "Locking in a powerful drum beat with the crowd jumping",
    influences: "Morgan Rose, Ray Luzier, Dave Grohl",
    favPet: "French Bulldog named Pierogi",
    favFoods: "Authentic Polish pierogis, kielbasa, and steak",
    favDrink: "Sparkling Water with Lemon",
    favCar: "Dodge Challenger SRT Hellcat",
    favSportToWatch: "Chicago Blackhawk Hockey",
    favBoardGame: "Risk",
    littleKnownFact: "I'm Polish, or wait, everyone knows that :)",
    funFact: "I'm Polish, or wait, everyone knows that :)",
    order: 0,
  },
  {
    _id: "bandMember-nick-cox",
    _type: "bandMember",
    name: "Nick Cox",
    slug: { _type: "slug", current: "nick-cox" },
    fullName: "NICK COX",
    memberNo: "NO. 004",
    role: "Guitars • Vocals • Piano",
    birthday: "March 19",
    zodiac: "Pisces",
    luckyNo: "19",
    color: "Midnight Navy",
    bestTrait: "Great listener",
    worstTrait: "Overthinking everything",
    favQuote: "The universe is a pretty big place... seems like an awful waste of space.",
    favLoveSong: '"Love of My Life" — Queen',
    favRockSong: '"Kashmir" — Led Zeppelin',
    favAlbum: "Physical Graffiti — Led Zeppelin",
    favBands: "Kiss, Queen, Zeppelin, Avenged Sevenfold",
    favSoundtrack: "Interstellar, Inception",
    favMovie: "American History X, Interstellar",
    fav7hSong: '"Take Me With You"',
    firstSong: "Stairway to Heaven",
    firstSongLearned: "Stairway to Heaven",
    favPlaceToPlay: "Outdoor summer amphitheaters",
    bestConcertSeen: "Led Zeppelin reunion / Queen + Adam Lambert",
    favTvShow: "Stranger Things, Game of Thrones",
    favCartoon: "Batman: The Animated Series",
    favMagazine: "Vintage Guitar",
    hobbies: "Chilling on the couch with vintage vinyl",
    hobbyAwayFromBand: "Chilling on the couch with vintage vinyl",
    bestFeeling: "A perfect guitar solo tone on stage",
    bestFeelingInWorld: "A perfect guitar solo tone on stage",
    influences: "Jimmy Page, Brian May, Synyster Gates",
    favPet: "Rescue tabby cat named Zeppelin",
    favFoods: "Chicago deep dish pizza & pasta",
    favDrink: "Cold Brew Coffee",
    favCar: "1969 Chevrolet Camaro",
    favSportToWatch: "Formula 1",
    favBoardGame: "Scrabble",
    littleKnownFact: "I love just staying home on my couch",
    funFact: "I love just staying home on my couch",
    order: 1,
  },
  {
    _id: "bandMember-adam-heisler",
    _type: "bandMember",
    name: "Adam Heisler",
    slug: { _type: "slug", current: "adam-heisler" },
    fullName: "ADAM BLAIR HEISLER",
    memberNo: "NO. 001",
    role: "Lead Vocals",
    birthday: "March 13",
    zodiac: "Pisces",
    luckyNo: "3",
    color: "Black",
    bestTrait: "I CARE TOO MUCH",
    worstTrait: "I CARE TOO MUCH",
    favQuote: "I'm always happy and never satisfied.",
    favLoveSong: '"She\'s Always a Woman" — Billy Joel',
    favRockSong: '"I Don\'t Like Your Neighbors" — AM Taxi',
    favAlbum: "The Stranger — Billy Joel",
    favBands: "Can't choose one — but he loves Ben Rector",
    favSoundtrack: "Grease 2",
    favMovie: "Whatever's on — but a good rom-com and a box of tissues will do it",
    fav7hSong: '"You and I"',
    firstSong: "One he wrote himself",
    firstSongLearned: "One he wrote himself",
    favPlaceToPlay: 'Anywhere they don\'t "boo"',
    bestConcertSeen: "Doesn't usually go to concerts",
    favTvShow: "Changes a lot — mostly girly shows like HIMYM and New Girl",
    favCartoon: "Ask Jett (his son)",
    favMagazine: "Reading?!",
    hobbies: "Being a dad",
    hobbyAwayFromBand: "Being a dad",
    bestFeeling: "Making someone happy",
    bestFeelingInWorld: "Making someone happy",
    influences: "God",
    favPet: "An alligator named Shoes",
    favFoods: "Healthy: kale & spinach salad with hard-boiled eggs. Not: pizza or burritos",
    favDrink: "Water",
    favCar: "Not a car guy",
    favSportToWatch: "Hahahahaha!!!!!!",
    favBoardGame: "Skip-Bo, as a kid",
    littleKnownFact: "Former Jr. black belt in Tae Kwon Do",
    funFact: "Former Jr. black belt in Tae Kwon Do",
    order: 2,
  },
  {
    _id: "bandMember-richard-hofherr",
    _type: "bandMember",
    name: "Richard Hofherr",
    slug: { _type: "slug", current: "richard-hofherr" },
    fullName: "RICHARD HOFHERR",
    memberNo: "NO. 003",
    role: "Guitars • Keys • Vocals",
    birthday: "May 17",
    zodiac: "Taurus",
    luckyNo: "77",
    color: "Electric Blue",
    bestTrait: "My Perspectives, Work Ethic, Loyalty",
    worstTrait: "Never sleeping",
    favQuote: "Life is all about perspectives. You can look at the glass half-empty and half-full.",
    favLoveSong: '"Love Bites" — Def Leppard',
    favRockSong: '"Photograph" — Def Leppard',
    favAlbum: "Hysteria — Def Leppard",
    favBands: "Def Leppard, Queen, Van Halen",
    favSoundtrack: "Blues Brothers, Star Wars",
    favMovie: "Blues Brothers, Star Wars",
    fav7hSong: '"Sing", "Diamonds", "Midwest Girls"',
    firstSong: "Rock of Ages — Def Leppard",
    firstSongLearned: "Rock of Ages — Def Leppard",
    favPlaceToPlay: "Every festival stage with 10,000 screaming fans",
    bestConcertSeen: "Def Leppard & Queen — Wembley",
    favTvShow: "Seinfeld & Shark Tank",
    favCartoon: "Looney Tunes",
    favMagazine: "Guitar World & Forbes",
    hobbies: "Audio engineering & songwriting",
    hobbyAwayFromBand: "Audio engineering & songwriting",
    bestFeeling: "Hearing 20,000 fans sing your song word for word",
    bestFeelingInWorld: "Hearing 20,000 fans sing your song word for word",
    influences: "Phil Collen, Steve Clark, Eddie Van Halen",
    favPet: "Golden Retriever named Gibson",
    favFoods: "Grilled steak & fresh fruit",
    favDrink: "Pure Mountain Spring Water",
    favCar: "Tesla Model S Plaid",
    favSportToWatch: "Chicago Bears & Bulls",
    favBoardGame: "Monopoly",
    littleKnownFact: "I have never had alcohol, drugs, cigarettes or a headache.",
    funFact: "I have never had alcohol, drugs, cigarettes or a headache.",
    order: 3,
  },
  {
    _id: "bandMember-mark-kennetz",
    _type: "bandMember",
    name: "Mark Kennetz",
    slug: { _type: "slug", current: "mark-kennetz" },
    fullName: "MARK KENNETZ",
    memberNo: "NO. 002",
    role: "Bass • Vocals • Uke • Guitar",
    birthday: "October 19",
    zodiac: "Libra",
    luckyNo: "19",
    color: "Green",
    bestTrait: "Being a Ninja",
    worstTrait: "n/a",
    favQuote: "The past is in Our heads, the future is in Our hands",
    favLoveSong: '"Crystal Ship" — The Doors',
    favRockSong: "n/a",
    favAlbum: "Sublime — 40 oz to Freedom",
    favBands: "Sublime, Led Zeppelin, Muse",
    favSoundtrack: "Matrix",
    favMovie: "Hot Fuzz, Anchorman, Big Lebowski",
    fav7hSong: '"Ethereal"',
    firstSong: '"People Are Strange" — The Doors',
    firstSongLearned: '"People Are Strange" — The Doors',
    favPlaceToPlay: "High-energy festival stages",
    bestConcertSeen: "Red Hot Chili Peppers",
    favTvShow: "Game of Thrones, Boardwalk",
    favCartoon: "Family Guy",
    favMagazine: "ESPN",
    hobbies: "Snowboarding, Blading, Biking, Motorcycle Riding, Saving Dolphins",
    hobbyAwayFromBand: "Snowboarding, Blading, Biking, Motorcycle Riding, Saving Dolphins",
    bestFeeling: "Riding a motorcycle on an awesome day",
    bestFeelingInWorld: "Riding a motorcycle on an awesome day",
    influences: "The Doors, Sublime, Led Zeppelin",
    favPet: "Kellieface",
    favFoods: "Bacon",
    favDrink: "Capt. N Diet",
    favCar: "Lexus GSF",
    favSportToWatch: "Football",
    favBoardGame: "Madden Xbox",
    littleKnownFact: "I'm a stage 2 carnivore, which means I eat anything with 2 legs or less, except bacon :)",
    funFact: "I'm a stage 2 carnivore, which means I eat anything with 2 legs or less, except bacon :)",
    order: 4,
  },
];

async function seed() {
  console.log("Seeding Sanity CMS with all 5 band member fact sheets...");

  for (const member of MEMBERS) {
    const res = await client.createOrReplace(member);
    console.log(`✓ Seeded ${member.name} (${res._id})`);
  }

  console.log("🎉 Successfully seeded all 5 band members into Sanity CMS!");
}

seed().catch((err) => {
  console.error("Error seeding Sanity CMS:", err);
  process.exit(1);
});
