const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const brainDir = "/Users/michaelscimeca/.gemini/antigravity-ide/brain";
const originalFile = path.join(__dirname, "../src/app/admin/page.tsx");
const patchFile = path.join(__dirname, "temp.patch");

// Revert admin page to baseline clean commit
console.log("Reverting admin page to clean baseline...");
execSync(`git checkout "${originalFile}"`);

// Find all transcript files
const transcriptFiles = [];
if (fs.existsSync(brainDir)) {
  const dirs = fs.readdirSync(brainDir);
  dirs.forEach(dir => {
    const fullPath = path.join(brainDir, dir, ".system_generated/logs/transcript_full.jsonl");
    const normalPath = path.join(brainDir, dir, ".system_generated/logs/transcript.jsonl");
    if (fs.existsSync(fullPath)) {
      transcriptFiles.push(fullPath);
    } else if (fs.existsSync(normalPath)) {
      transcriptFiles.push(normalPath);
    }
  });
}

console.log(`Found ${transcriptFiles.length} transcript log files to process.`);

// Extract all successful CODE_ACTION diffs
const patches = [];

transcriptFiles.forEach(tPath => {
  const content = fs.readFileSync(tPath, "utf8");
  const lines = content.split("\n").filter(Boolean);
  lines.forEach((line, lineNum) => {
    try {
      const data = JSON.parse(line);
      if (
        data.type === "CODE_ACTION" &&
        data.status === "DONE" &&
        data.content &&
        data.content.includes("src/app/admin/page.tsx") &&
        data.content.includes("[diff_block_start]")
      ) {
        const startIdx = data.content.indexOf("[diff_block_start]");
        const endIdx = data.content.indexOf("[diff_block_end]");
        if (startIdx !== -1 && endIdx !== -1) {
          const diffContent = data.content
            .substring(startIdx + "[diff_block_start]".length, endIdx)
            .trim();
          
          const patchText = `--- a/src/app/admin/page.tsx\n+++ b/src/app/admin/page.tsx\n${diffContent}\n`;
          
          patches.push({
            created_at: data.created_at || "2000-01-01T00:00:00Z",
            step_index: data.step_index,
            patchText,
            origin: path.basename(path.dirname(path.dirname(path.dirname(tPath))))
          });
        }
      }
    } catch (err) {}
  });
});

// Sort patches chronologically
patches.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));

console.log(`Extracted ${patches.length} patches to apply.`);

let successCount = 0;
let skippedCount = 0;

patches.forEach((patch, idx) => {
  fs.writeFileSync(patchFile, patch.patchText, "utf8");
  
  try {
    // --batch: non-interactive
    // -N: forward patches only (do not apply reversed/already applied patches)
    // -F3: maximum fuzz
    execSync(`patch --batch -N -p1 -F3 < "${patchFile}"`, { stdio: "ignore" });
    successCount++;
  } catch (err) {
    // If it fails, it means the patch was already applied, reversed, or conflicted.
    // We just skip it and let patch utility continue with subsequent forward patches.
    skippedCount++;
  }
});

// Clean up
if (fs.existsSync(patchFile)) {
  fs.unlinkSync(patchFile);
}

// Clean up reject files (.rej) generated by failed patch hunks
try {
  execSync(`find src/app/admin -name "*.rej" -delete 2>/dev/null`);
} catch (err) {}

console.log(`SUCCESS: Applied ${successCount} patches (skipped/already-present: ${skippedCount}).`);

// View lines to make sure
const resultLines = fs.readFileSync(originalFile, "utf8").split("\n").length;
console.log(`Final file line count: ${resultLines}`);
